### ISSUE TITLE
That's great,but Some insufficiency

### ISSUE THREAD

**Issue by solio** [gloomyson/StarCraft#15]
There is a little latency when I select the unit, and when I move on the unit, the unit dosen't show the "mine unit or enemy's unit" border (red is enemy or green is mine).
I view the code,that "Game.getSelectedOne" method implements by checking all units to judge whether the unit is around the mouse click position.Why not use a two dimension array to record the element's position and quick to find them.
Excuse my terrible expression.Can I be involved in developing and contribute my code to this repo?

**Comment by gloomyson** [comment]
1.What do you exactly mean by 'dosen't show the "mine unit or enemy's unit" border', this kind of border is shown when you select that unit, or you just mean cursor should becomes green or red when mouse hover on that unit?
2.All the units have its own location (x,y) exactly, but it's pixel unit, because unit size are different, from Zergling to BattleCruiser, please explain what is your two dimension array mean
3.Anyone can contribute to this project by simply fork my repo, make their changes and submit pull request.

**Comment by solio** [comment]
1.I mean when mouse hover the unit and show the border.
2."two dimension array" is a bad idea,please ignore.
